language: python
sudo: required
cache:
  directories:
    - buildout-cache
python:
  - 2.7
node_js:
  - "6.1"
install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap-buildout.py --setuptools-version=8.3 -c travis.cfg
  - bin/buildout -Nc travis.cfg
  - cd ide && npm install && npm run build && cd ..
script:
  - bin/test -s Products.CMFPlomino  --all

notifications:
  irc:
    - "irc.freenode.org#plomino"
