language: python
sudo: required
cache:
  directories:
    - buildout-cache
python:
  - 2.7
node_js:
  - "6.0"
  - "5.6"
  - "4.3"
before_install:
  - sudo apt-get update
  - wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu52_52.1-3ubuntu0.4_amd64.deb
  - sudo dpkg -i libicu52_52*.deb
  - npm i -g npm@3
  - npm i -g typescript@2.1.4
  - npm --version
  - node --version
  - tsc --version
  - sudo apt-get install geckodriver chromedriver
install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap-buildout.py --setuptools-version=8.3 -c travis.cfg
  - bin/buildout -Nc travis.cfg
  - npm cache clean
  - npm set registry http://registry.npmjs.org
  - npm update -g
  - cd ide && npm install && npm run build && cd ..
script:
  - bin/test -s Products.CMFPlomino  --all

notifications:
  irc:
    - "irc.freenode.org#plomino"
